# Generated by Django 3.1.6 on 2021-02-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome do Serviço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Institucional',
                'verbose_name_plural': 'Institucionais',
                'ordering': ['id'],
            },
        ),
    ]
