# Generated by Django 3.1.6 on 2021-02-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_institutional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institutional',
            new_name='Institutionals',
        ),
    ]
