# Generated by Django 3.1.6 on 2021-02-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0004_auto_20210211_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionals',
            name='slug',
            field=models.CharField(default=0, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
