# Generated by Django 3.1.6 on 2021-02-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0005_institutionals_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionals',
            name='name',
            field=models.TextField(verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='CategoryArchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='backends.categoryarchives')),
            ],
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='archives/%Y%m%d%H%i%s/')),
                ('name', models.TextField(verbose_name='Nome')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_archives', to='backends.categoryarchives')),
            ],
        ),
    ]
