# Generated by Django 3.1.6 on 2021-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_auto_20210212_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archives',
            options={'ordering': ['id'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='categoryarchives',
            options={'ordering': ['id'], 'verbose_name': 'Categoria do Modelo', 'verbose_name_plural': 'Categorias dos Modelos'},
        ),
        migrations.AlterField(
            model_name='archives',
            name='docfile',
            field=models.FileField(upload_to='archives/%Y%m%d%H%m%s/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoryarchives',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Serviço'),
        ),
    ]
