# Generated by Django 3.1.6 on 2021-02-12 17:00

import backends.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_auto_20210212_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archives',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='categoryarchives',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryarchives',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='docfile',
            field=models.FileField(upload_to=backends.models.Archives.content_file_name, verbose_name='Arquivo'),
        ),
    ]
