# Generated by Django 3.1.6 on 2021-02-14 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0008_auto_20210212_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarchives',
            name='parent',
        ),
        migrations.AddField(
            model_name='categoryarchives',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_archive', to='backends.categoryarchives'),
        ),
    ]
