# Generated by Django 3.1.6 on 2021-02-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0009_auto_20210214_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarchives',
            name='archive',
        ),
        migrations.AddField(
            model_name='categoryarchives',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='backends.categoryarchives'),
        ),
    ]
