# Generated by Django 3.1.6 on 2021-02-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0010_auto_20210214_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryarchives',
            old_name='sub_category',
            new_name='mother_category',
        ),
    ]
