# Generated by Django 3.1.6 on 2021-02-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0011_auto_20210214_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_archives', to='backends.categoryarchives'),
        ),
        migrations.AlterField(
            model_name='categoryarchives',
            name='mother_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='backends.categoryarchives'),
        ),
    ]
