# Generated by Django 3.1.6 on 2021-02-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0012_auto_20210215_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='backends.categoryarchives'),
        ),
    ]
