# Generated by Django 3.1.6 on 2021-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0013_auto_20210215_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
